name: CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1.1.1
    - run: bun install
    - run: bun run build
